name: tag-merge

on:
  workflow_call:

jobs:
  tag-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tag and push.
        run: |
          git config --global user.name 'ivanov-slk'
          git config --global user.email 'ivanov-slk@users.noreply.github.com'
          git fetch
          git checkout $GITHUB_HEAD_REF

          CURRENT_TAG="$(echo $(sed '5q;d' CHANGES.md) | sed 's/# //g')"
          CURRENT_COMMIT_ID=$(git rev-parse HEAD)

          git tag -a $CURRENT_TAG -m $CURRENT_COMMIT_ID
          git push --tags

          sleep 5  # Make sure the tag has been pushed before other steps are executed.
