name: version-tag-merge

on:
  push:
    branches: [master]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the latest tag and the commit id.
        run: |
          git config --global user.name 'ivanov-slk'
          git config --global user.email 'ivanov-slk@users.noreply.github.com'
          git fetch
          git checkout $GITHUB_HEAD_REF

          CURRENT_TAG="$(echo $(sed '5q;d' CHANGES.md) | sed 's/# //g')"
          CURRENT_COMMIT_ID=$(git rev-parse HEAD)

          git tag -a $CURRENT_TAG -m $CURRENT_COMMIT_ID
          git push --tags --dry-run

  call-build-and-publish-image:
    uses: ./.github/workflows/build-and-publish-image.yml
