name: version-tag-merge

on:
  push:
    branches: [master]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: actions/checkout@v3

      - name: Get the latest tag and the commit id.
        id: latest_tag_and_commit_id
        run: |
          git config --global user.name 'ivanov-slk'
          git config --global user.email 'ivanov-slk@users.noreply.github.com'
          git fetch
          git checkout $GITHUB_HEAD_REF

          CURRENT_TAG="$(echo $(sed '5q;d' CHANGES.md) | sed 's/# //g')"
          CURRENT_COMMIT_ID=$(git rev-parse HEAD)

          echo "::set-output name=current_tag::${CURRENT_TAG}"
          echo "::set-output name=current_commit_id::${CURRENT_COMMIT_ID}"

          # git tag -a $CURRENT_TAG -m $CURRENT_COMMIT_ID
          # git push --tags

      - name: Tag.
        id: tag_version
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.latest_tag_and_commit_id.outputs.latest_tag }}
